### PR TITLE
Updated Set 3 and automated card updating

### PR DESCRIPTION
**Pull request by bbugh**
The cards have been updated for set 3. I bumped the version number to 1.6.

Also, there were a lot of unnecessary manual steps in the build process, plus some issues like lein was using a text file instead of a `clj` file, frak wasn't configured fully, python was using a different name than EternalWarCry's json, etc. I took the liberty of automating it, so you just have to run a couple of steps next time. I updated the README to reflect it, but here's the steps:

1. `cd frak`
2. `wget -N https://eternalwarcry.com/content/cards/eternal-cards.json`
3. `python compile_dict.py`
4. `cat compile_regex.clj | lein repl`

Or you can just do it in one line like I was:

`wget -N https://eternalwarcry.com/content/cards/eternal-cards.json && python compile_dict.py && cat compile_regex.clj | lein repl`

Voilá.

## Changes
- added `project.clj` so lein can handle installing/loading frak automatically
- changed python to load `eternal-cards.json` instead of just `cards.json` so it matches the eternalwarcry filename
- moved `frak_console.txt` to `compile_regex.clj`:
  - properly loads frak
  - deletes the existing file before writing
  - writes straight to the `card_match.txt` instead of intermediary `reg.txt`

### CODE REVIEW

**Comment by bbugh** [comment]
image

**Comment by BearHanded** [comment]
Thanks a ton. This was on my agenda over the holidays. I'll give this a go tonight and if it goes well, move it up to the chrome store.

**Comment by bcm32** [comment]
I'm going to go ahead and merge this. Where did you get the updated card list?

**Comment by bbugh** [comment]
You're welcome! Glad to support. Thanks for doing the hard work of actually making the thing and supporting the community.

**Pull request merged**
